### ISSUE TITLE
File saved with JLD2 can't be read, from identical OS and JLD2 version

### ISSUE THREAD

**Issue by Datseris** [JuliaIO/JLD2.jl#55] opened 2018-01-15 17:01 UTC
Hello, I am facing a serious problem, namely that a file saved with `JLD2` version `0.0.5` and `FileIO` cannot be read from the same OS with the same version of `JLD2`. 

It is really weird for me because I have a bunch of files (computed with different parameters of a model) and most of them work perfectly.

Notice that for *all* of my files being computed, STDERR was empty, and STDOUT was exactly as expected (reporting some timings of computations and whatever).

I know paste my error messages:

![image](https://user-images.githubusercontent.com/19669089/34953714-f8d129d8-fa1d-11e7-8b71-7373d3abb9dc.png)

which does not work. However, another file, produced by the identical code with one parameter different (positive instead of negative energy):

![image](https://user-images.githubusercontent.com/19669089/34953743-0cccfdd6-fa1e-11e7-8175-7d127cfc6776.png)

I have no reason to believe that there is something wrong with the data of the first case, as I have done the computation for one sub-case and it work.

I am more than willing to share the 2 files presented here if they can help (I really need some help since I cannot load some long-running cluster results).

**Comment by Datseris** [comment] 2018-01-15 17:12
I have noticed that **all** my data that have negative energy cannot be loaded.

Can there be an issue with having `-` in the file name?

**Comment by ararslan** [comment] 2018-01-15 18:17
> Can there be an issue with having `-` in the file name?

If you save it as something like test.jld2 and try to load that, does it work?

**Comment by Datseris** [comment] 2018-01-15 18:19
Unfortunately to save it with a different name, I would have to re-create the data and thus submit a lot of hours of cluster work.

Simply renaming the file did not fix the issue however. I will try to produce a similar dataset with a much smaller system on my laptop in the mean-time.

**Comment by ararslan** [comment] 2018-01-15 18:22
If renaming the file didn't work then I wouldn't bother generating a new file just to test this. I think we can rule out an issue with the file name.

**Comment by Datseris** [comment] 2018-01-25 10:35
I have re-run all my simulations, made extra care to be sure that JLD2 version is everywhere 0.0.5 and now I can load the data.

I wonder whether this was an issue on my end or something weird happened somehow. I am closing this assuming it was an issue on my end. If you think ottherwise you can reopen.

**Comment by Datseris** [comment] 2018-02-13 13:26
@ararslan Hello, with many tears I return to this issue once more.

It happened to me again, and once again I can't load my data... :(

Versions:
```
 - FileIO                        0.6.1
 - JLD2                          0.0.5
```

I am 100% certain that my data has been produced on the same versions of FileIO and JLD2. I can also tell you with certainty that the data were saved on a linux, but I am trying to load them on a Windows 10.

The problem is the same for both linux or windows when I try to load the file:
```
file = "husimis_B=10.0_Dk=0.2_wid=80_leng=100_w=30.0_V0=0.4_E=-0.1.jld2"
"husimis_B=10.0_Dk=0.2_wid=80_leng=100_w=30.0_V0=0.4_E=-0.1.jld2"

julia> a = load(file)
Error encountered while loading "/scratch05/datseris/KleinGraphene/data/husimis/husimis_B=10.0_Dk=0.2_wid=80_leng=100_w=30.0_V0=0.4_E=-0.1.jld2".
Fatal error:
ERROR: JLD2.InvalidDataException()
Stacktrace:
 [1] read_obj_start(::JLD2.MmapIO) at /home/datseris/.julia/v0.6/JLD2/src/object_headers.jl:47
 [2] isgroup(::JLD2.JLDFile{JLD2.MmapIO}, ::JLD2.RelOffset) at /home/datseris/.julia/v0.6/JLD2/src/object_headers.jl:74
 [3] getindex(::JLD2.Group{JLD2.JLDFile{JLD2.MmapIO}}, ::String) at /home/datseris/.julia/v0.6/JLD2/src/groups.jl:103
 [4] loadtodict!(::Dict{String,Any}, ::JLD2.JLDFile{JLD2.MmapIO}, ::String) at /home/datseris/.julia/v0.6/JLD2/src/loadsave.jl:114
 [5] #jldopen#31(::Array{Any,1}, ::Function, ::JLD2.##44#45, ::String, ::Vararg{String,N} where N) at /home/datseris/.julia/v0.6/JLD2/src/loadsave.jl:4
 [6] #load#43(::Array{Any,1}, ::Function, ::FileIO.File{FileIO.DataFormat{:JLD2}}) at /home/datseris/.julia/v0.6/JLD2/src/loadsave.jl:126
 [7] load(::FileIO.File{FileIO.DataFormat{:JLD2}}) at /home/datseris/.julia/v0.6/JLD2/src/loadsave.jl:126
 [8] eval(::Module, ::Any) at ./boot.jl:235
 [9] #load#20(::Array{Any,1}, ::Function, ::FileIO.File{FileIO.DataFormat{:JLD2}}) at /home/datseris/.julia/v0.6/FileIO/src/loadsave.jl:98
 [10] load(::FileIO.File{FileIO.DataFormat{:JLD2}}) at /home/datseris/.julia/v0.6/FileIO/src/loadsave.jl:86
 [11] #load#13(::Array{Any,1}, ::Function, ::String) at /home/datseris/.julia/v0.6/FileIO/src/loadsave.jl:52
 [12] load(::String) at /home/datseris/.julia/v0.6/FileIO/src/loadsave.jl:52
```

I can tell you something new, something that really might help.

**This specific file contains a lot of Arrays where one of the dimensions is 1, like a vector with 1 element, or a 1x1000 matrix or a 1000x1000x1x6 array, etc.**

Could it be that somehow this messes things up?

Once again I am willing to share my data if this will help you.

**Comment by Datseris** [comment] 2018-02-13 13:29
Another info: My STDOUT is perfectly fine while my program runs, i.e. I get no warnings even during the saving of the file.  My STDERR is complitely empty, I get no errors while the program runs and finishes.

**Comment by ararslan** [comment] 2018-02-13 20:29
Hm, I'm really not sure and I don't have time to investigate deeply right now. @simonster, do you have any ideas?

**Comment by tscode** [comment] 2018-02-15 16:54
I can confirm this (or at least a closely related) issue. I use `JLD2` to save trained convolutional network models (using `Knet.jl`). When I save a freshly initialized model in the REPL, everything works fine, and I can load the model.

When I train the network (updating data in `Float32` arrays) on a cluster-submission system, save it (`A.jld2`) and then try to load it, I get the same error as @Datseris. Interestingly, when I also save the model during the same run with julia's serialization functions, and then load it with `deserialize` in the REPL afterwards, I can again save the loaded model using `JLD2` (`B.jld2`). This file, then, **can** be loaded successfully. So it is not the data itself that causes the corruption in `A.jld2`.

I looked at the hex-differences between the binaries `A.jld2` and `B.jld2`. They are mostly identical - up to small regions, where `A.jld2` contains a sequence of 0 entries. These regions (there were three of them in my case) always started where `B.jld2` would read `4f4844520201360`. Not sure if this helps, though. Unfortunately, I don't know anything about HDF5 files.

Currently, I have the feeling that this only happens when I submit my simulation through the submission system (condor), and not when I start the simulation on the respective nodes by hand. I am, however, not sure about that yet. Still, this feels quite puzzling.

The cluster nodes (regular PCs in my university's network) run Julia 0.6.2 and JLD 0.2.0 on linux.

**Comment by Datseris** [comment] 2018-02-15 17:02
Thanks @tscode for giving much more details here, since I lack knowledge of saving formats etc.

I can also confirm that this happens for me when I use our submission system (called `qsub`) so maybe it can be somehow related.

You can also confirm that the STDERR is empty when the simulation is finished, even though the file cannot actually be loaded?

**Comment by tscode** [comment] 2018-02-15 18:52
Yes, I can confirm that. `JLD2` does not complain, and everything proceeds without errors.

However, my guess that starting the simulation by hand would make a difference is false. The problem is that different PCs on the cluster seem to create different versions of `.jld2` files that are incompatible. I can now reliably create `.jld2` files on node A, such that the file can be loaded from node A but not from other nodes B and C, and vice versa.

Note that all tested nodes (A, B, and C) in this example make use of the very same julia binaries and packages, since julia is only installed locally in a shared folder that all systems have access to. They also have the same CPU and OS (Fedora 25).

On my laptop (with Arch linux, but same Julia and JLD versions), I can open none of the files created by A, B, or C. The crashes always happen due to `os.signature = 0x00000000` in the function `read_obj_start` in the file `object_headers.jl` after the function has been called several times sucessfully.

**Comment by simonster** [comment] 2018-02-16 07:53
My guess is that your cluster uses a network file system that is not handling `mmap` properly. If you're okay with using the `jldopen` interface, you could try:

```julia
f = jldopen(fn, true, true, true, IOStream)
```

which directs JLD2 not to use `mmap`. Unfortunately, this mode is many times slower, and it has never been tested in the wild (although it is tested in the package tests), so you may run into other issues.

**Comment by tscode** [comment] 2018-02-16 08:58
You seem to be right. I cannot reproduce the error if I use `jldopen` in the way you suggested. That is fine for my use case.

**Comment by Datseris** [comment] 2018-02-16 09:56
@simonster sorry, but could you please give a bit more info on how to actually use `jldopen` ? I am sorry but I am very novice on the topic.

I use `save("file.jld2", dictionary)` at the moment, without considering arguments or `IOStream`. How to modify this to use `f = jldopen` ?

**Comment by tscode** [comment] 2018-02-16 11:58
Something like
```julia
jldopen("file.jld2", true, true, true, IOStream) do file
  for (key, value) in dictionary
    write(file, key, value)
  end
end
```
should do it. Maybe there is a way to write dictionaries directly?

**Comment by mweastwood** [comment] 2018-02-25 23:09
I seem to be able to reproduce this issue fairly regularly. An object that was supposedly written to the file is actually just all zeroes. I've seen lustre struggle with mmap before so I guess this isn't all that surprising. For posterity here's the version of lustre that we have running:

```
$ cat /proc/fs/lustre/version
lustre: 2.8.0
kernel: patchless_client
build:  2.8.0-RC5--PRISTINE-2.6.32-573.12.1.el6_lustre.x86_64
```

Would you accept a PR that adds a check for `os.signature == 0x00000000` in `read_obj_start(io::IO)` and outputs a more informative error message?

Perhaps we could also add an `mmap=false` keyword to `jldopen` that makes that option a little more discoverable?

**Comment by iblis17** [comment] 2018-03-07 08:39
I also ran into this issue on WRDS cluster. I saved my JLD2 into shared storge (via NFS I guess).

**Comment by pengwyn** [comment] 2018-05-03 07:01
I also ran into this issue with a cluster I built myself. It is an issue when saving to an NFS share.

I have a very generic NFS setup so I'm surprised that mmap is failing there. In fact, reading http://nfs.sourceforge.net/, it suggests that it is common for applications using mmap to rely on functionality that is not part of the mmap standard.

> D8. When my application uses memory-mapped NFS files, it breaks. Why?
> A. Usually this is because application developers rely on certain local file system behaviors to guarantee data consistency, rather than reading the mmap man pages carefully to understand what behavior is required by all file system implementations. Some examples:
> 
> Although some implementations of munmap(2) happen to write dirty pages to local file systems, the NFS version of munmap(2) does not. An msync(2) call is always required to guarantee that dirty mapped data is written to permanent storage. A subtle ramification of the Linux NFS client's treatment of munmap(2) is that does not consider munmap(2) to be a close operation for the purposes of close-to-open cache coherency.
> 
> The distinction between the MS_SYNC and MS_ASYNC flags is also important. MS_ASYNC will force dirty mapped pages to permanent storage eventually. Only MS_SYNC guarantees that the pages are written before msync(2) returns to your application. Therefore applications should use msync(MS_SYNC) to serialize data writes to mapped files.
> 
> Finally, the Linux NFS client may not flush dirty mapped pages when a file descriptor is closed via close(2). Oftentimes during close processing, the client may flush mapped pages along with pages dirtied by a write(2) call, but this behavior is not guaranteed. Many applications will open a file, map it, then close it and continue using the map. The behavior described above is an attempt to optimize the performance of this use case.

Could it be that JLD2 is making one of these errors? I admit I haven't looked into the source (and doubt that I would be able to identify this if I did) so I apologise if I'm pointing fingers when I shouldn't be!

**Comment by simonster** [comment] 2018-05-04 05:03
It does call [msync](https://github.com/simonster/JLD2.jl/blob/c1b9521d6a1b920bfa498f6766c5d5ff62c985c4/src/mmapio.jl#L169) although it's quite possible that it doesn't do it properly. It's probably easiest if someone who can reproduce this issue could try to debug this.

**Comment by ksmcreynolds** [comment] 2018-06-05 15:19
I also ran into this problem and was able to isolate the size dependence of this bug. It occurs for file sizes that are 262784 bytes or larger. The following code will reproduce the bug when the file is written from a compute node on my cluster and read from the login node or a different compute node.
```Julia
using JLD2
abcde = rand(2^15 - 10)
abcdef = copy(abcde)
# abcde.jld2 is 262783 bytes and loads fine
@save "abcde.jld2" abcde
# abcdef.jld2 is 262784 bytes and produces an error when loading
@save "abcdef.jld2" abcdef
# nommap.jld2 is 262784 bytes and loads fine
jldopen("nommap.jld2", true, true, true, IOStream) do file
    file["abcdef"] = abcdef
end
```
I haven't tested it extensively for other variable types, but using an array of Float32 (`rand(Float32, 2^16 - 20)`) instead of Float64 gave the same size limit. While I don't have a great understanding of the JLD2 code, it is interesting to note that `262784 = 2^18 + 512 + 128` which is just larger than [`const FILE_GROW_SIZE = 2^18`](https://github.com/simonster/JLD2.jl/blob/master/src/mmapio.jl#L10) in mmapio.jl.

**Comment by mweastwood** [comment] 2018-06-05 17:36
Unfortunately your example doesn't reproduce the bug for me (lustre 2.8.0). I can load both `abcde.jld2` and `abcdef.jld2` on a different compute node without error. I've also bumped up the number of elements and still can't seem to trigger the error. What file system is your cluster using?

**Comment by ksmcreynolds** [comment] 2018-06-05 18:26
It's using NFS (v3 I believe) on Debian 8.

**Comment by mweastwood** [comment] 2018-06-07 03:19
It's great to hear that you are narrowing in on the solution! Unfortunately I've long since switched over all my code to use the non-mmap based interface, and I'm in the middle of writing up my thesis, so I don't quite have the bandwidth at the moment.

On the other hand, I think it's fair to say that I've put the non-mmap code path through some battle testing and haven't hit any issues.

**Comment by ksmcreynolds** [comment] 2018-06-08 13:51
@pengwyn I tried both of your methods, and they work for me as well. However, running the benchmarks I did notice a slow down. Specifically focusing on the JLD write benchmark, it was between 1x-2x slower using the first option (`truncate`) and up to 10x slower for some tests using the second option (`msync`) compared to the original code. After running the benchmarks I realized that benchmarks script was writing to the `/tmp` directory which on our cluster is an XFS file system local to the node. When I tried writing to the shared NFS file system the results were even worse with times over 100x slower for `truncate` and 40x slower for `msync` compare to the original code writing to the NFS file system (NFS was about 2x slower than XFS for the original code). I should note that the writes for `int_vector` and `complex128_vector` only showed ~1.5x-2.5x slow down. The times I used were the median times, and although some only ran one sample I ran the script multiple times to confirm they were not a fluke.

**Comment by pengwyn** [comment] 2018-06-09 08:12
Ah I didn't realise that. Yes the benchmarks are about 20x slower for writing over NFS using either of the two approaches above. Strangely I get a pretty much even slowdown (always around 20x). The filesystem itself is EXT4.

I also have a glusterfs setup on this cluster. In this case, things were about 10-20x slower (as I might expect with a distributed filesystem) but there was no real pattern in the difference between the three aproaches. Sometimes the msync approach was even faster.

I wonder if I'm missing something, because the problem only seems to happen for an individual array being larger than `FILE_GROW_SIZE`. The files themselves can be much larger without giving rise to this bug. Maybe there's something odd with the case of `newsz = newend - ptr` branch...

**Comment by tyleransom** [comment] 2018-06-14 20:01
Thanks @pengwyn and @ksmcreynolds. I've run into this same problem and your suggestions (temporarily) fixed my issue.

**Comment by ksmcreynolds** [comment] 2018-07-03 15:27
@pengwyn The variability I got was probably due to traffic on the filesystem. Performance varies wildly depending on usage.

In other news, there appears to be an upper limit on the size dependence. The following code produces two files that are both 1049299 bytes (slightly larger than 2^20). `abcdefghi.jld2` hits the bug while `a.jld2` works fine. Larger array sizes also seem to work fine.
```julia
abcdefghi = rand(2^17)
a = rand(2^17+1)
@save "abcdefghi.jld2" abcdefghi
@save "a.jld2" a
```
I also find that the bug is dependent on the individual array size, not the file size for both the lower and upper bound.

**Comment by taylormcd** [comment] 2018-12-05 22:11
Any progress towards fixing this?  Just encountered this issue myself and now have to rerun a few things because of it.

**Comment by pengwyn** [comment] 2018-12-09 04:14
I ran out of time trying to isolate the root cause of the issue. In the end my work around was to write a temporary file, e.g. `output_temp.jld2`, and then copy this file to `output.jld2` and afterwards delete the temporary file.

This works in my case because I assume the file is cached in memory on the guest node. The copy command then writes everything fresh without using mmap and without having to read the corrupted file.

**Comment by ksmcreynolds** [comment] 2018-12-10 13:00
I also write to `/tmp` which is not a part of the NFS in my case. Please note if you have files >2 GB that you will run into [this issue](https://github.com/JuliaLang/julia/issues/14574) using the `cp` command in `julia`.

**Comment by montyvesselinov** [comment] 2019-01-30 19:06
I confirm this error JLD2 on Ubuntu. There is no problem running the exactly the same script on Mac.

```
julia> a=JLD.load("./ABA/results/xp2-3_12_12.jld")
┌ Warning: type TensorDecompositions.SPNNTuckerStateOld not present in workspace; reconstructing
└ @ JLD ~/.julia/packages/JLD/1BoSz/src/jld_types.jl:703
Dict{String,Any} with 1 entry:
  "t" => TensorDecompositions.Tucker{Float64,3}[Tucker{Float64,3}(([2.80836 0.0606092 … 0.0 0.0; 2.75255 0.0590717 … 0.0 0.0; … ; 2.74954 0.070929 … 0.0 0.0; 2.80536 …

julia> FileIO.save("./ABA/results/xp2-3_12_12.jld2", a)

julia> FileIO.load("./ABA/results/xp2-3_12_12.jld2")
Error encountered while loading "/scratch/er/monty/rMF.jl/ABA/results/xp2-3_12_12.jld2".
Fatal error:
ERROR: JLD2.InvalidDataException()
Stacktrace:
 [1] handle_error(::JLD2.InvalidDataException, ::FileIO.File{FileIO.DataFormat{:JLD2}}) at /home/vvv/.julia/packages/FileIO/YJO7Z/src/error_handling.jl:80
 [2] handle_exceptions(::Array{Any,1}, ::String) at /home/vvv/.julia/packages/FileIO/YJO7Z/src/error_handling.jl:75
 [3] #load#27(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::FileIO.File{FileIO.DataFormat{:JLD2}}) at /home/vvv/.julia/packages/FileIO/YJO7Z/src/loadsave.jl:193
 [4] load(::FileIO.File{FileIO.DataFormat{:JLD2}}) at /home/vvv/.julia/packages/FileIO/YJO7Z/src/loadsave.jl:172
 [5] #load#13(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::String) at /home/vvv/.julia/packages/FileIO/YJO7Z/src/loadsave.jl:118
 [6] load(::String) at /home/vvv/.julia/packages/FileIO/YJO7Z/src/loadsave.jl:118
 [7] top-level scope at none:0
```

**Comment by mloubout** [comment] 2019-03-27 11:35
I have errors on Mac and redhat, can't open my JLD2 files anymore

**Comment by steffenkaminski** [comment] 2020-01-16 12:43
saving as in https://github.com/janEbert/SMWLevelGenerator/commit/d211650f199114c509a162ad7f8364ae0725dd40 works for my scipts in the cluster.

**Comment by JonasIsensee** [comment] 2020-07-06 08:24
Hi,
JLD2 is just too good a format to not get this bug fixed...
I did some digging over the weekend.
I still did not find the root cause of the problem but I feel that I got quite a bit closer.
Here's a summary if someone wants to help me out here:

## Restating the problem
JLD2 does not properly write files to disk when one of the field size is very close to `FILE_GROW_SIZE` 
and one is working on a network file system (NFS).
```
using JLD2
w = rand(4,4,64,64)
@save "test.jld2" w
```

# Possible workarounds:
@pengwyn  suggested two solutions that work for me but have been reported to be MUCH slower on non NFS systems

> That also seems to cause the error for me @ksmcreynolds. I think it is due to the `pwrite` call in the `grow` function.
> 
> I can stop the bug from happening by doing either:
> 
>     1. Forcing the `grow` function to use `truncate` by commenting out the [if Compat.Sys.islinux()](https://github.com/simonster/JLD2.jl/blob/master/src/mmapio.jl#L121) line (i.e. making it simply `if false`).
> 
>     2. Forcing an `msync` before the `grow` function is called [here](https://github.com/simonster/JLD2.jl/blob/c1b9521d6a1b920bfa498f6766c5d5ff62c985c4/src/mmapio.jl#L139)

3. Replacing `pwrite` with `ftruncate` also worked for me.

4. Replace this https://github.com/JuliaIO/JLD2.jl/blob/bb1f4b482c2793c6b92ff588e005473b41fbac42/src/mmapio.jl#L138
line by something like
```
 newsz = Int(max(newend - ptr + FILE_GROW_SIZE, io.curptr - ptr + FILE_GROW_SIZE))
```
to ensure that there is always plenty of space at the end of the file.

## Towards finding the actual problem

@pengwyn already guessed that
> Maybe there's something odd with the case of newsz = newend - ptr branch...
which I definitely agree with. (This is essentially solution 4)

This brings me to my suspicion about the root cause of the problem.
I think there may potentially be something off about the length computation (space allocation) of the header bytes.
For examples:
Change the line from solution 4 to
```
    newsz = Int(max(newend - ptr, io.curptr - ptr)) + FILE_GROW_SIZE
```
which will grow the file by an extra 102 bytes when we save the array. (Only the array is large enough to trigger that branch)
Note also that the header of the data segment is 103 bytes, so this is probably not just a coincidence.
See here for reference:
https://github.com/JuliaIO/JLD2.jl/blob/bb1f4b482c2793c6b92ff588e005473b41fbac42/src/datasets.jl#L370
 

### Trying it out
So with the 102 extra bytes this
```
using JLD2
w = rand(4,4,64,64)
@save "test.jld2" w
```
produces a valid file for me.
However just adding a small extra field breaks things again (`InvalidDataException`)
```
v = rand(5)
@save "test.jld2" w v
```
Increasing the size of the extra field to `v = rand(500)` changes the error on loading to
`UndefRefError: access to undefined reference` which may confirm some fields are not written at the correct byte locations.
(and here maybe end up outside the actual file)

I used the debugger to step through the code quite a few times but have not been able to spot the problem.

## The way forward
It be best if we found the actual reason for this bug but I think in the meantime it would be good to use one of these
_workarounds_ to avoid the problem. My personal favourite is solution no 4 as it should not change the behaviour significantly in any setting because it only gathers a bit of extra space.
To all those that can reproduce the bug: Can you please test out these suggested modifications to see if they solve the problem for you?

What are your thoughts?

**Comment by JonasIsensee** [comment] 2020-08-31 08:53
It is now possible to pass `iotype=IOStream` as a keyword argument to `save` and to do
`@save "filename.jld2" {iotype=IOStream} var`
as a workaround for this bug.

**Comment by dpo** [comment] 2020-09-05 00:42
I also just came across this bug and it's really not fun when the data takes a week to generate.

**Comment by lhupe** [comment] 2020-09-05 05:00
@dpo have you tried this workaround? If you are lucky, you can still save your data

> In the end my work around was to write a temporary file, e.g. output_temp.jld2, and then copy this file to output.jld2 and afterwards delete the temporary file.

I'm afraid we can't offer anything better than workarounds for now — Jonas (and many before him) have spent days trying to fix this particular bug, unfortunately without success so far.

@JonasIsensee maybe this bug (and its many workarounds) should be mentioned in the README to avoid data loss for new users, who aren't aware of this issue.

**Comment by JonasIsensee** [comment] 2020-09-05 06:32
@lhupe 
You are probably right.
I hadn't really given up on fixing this so I delayed putting it in there but this should be done.

**Comment by dpo** [comment] 2020-09-05 14:42
@lhupe Thanks to tmux, my Julia session was still alive and the workaround https://github.com/JuliaIO/JLD2.jl/issues/55#issuecomment-366166343 (the first one I came across) worked for me. Thank you all for trying to find a solution to this issue. If that workaround is guaranteed to work in all cases, maybe it should be the default. Correct is better than fast.

**Comment by JonasIsensee** [comment] 2020-09-07 06:48
@dpo
I'm relieved to hear that you were able to recover your data.

In many cases I would agree with you but in this case I don't think moving to `IOStream` should be the default.
The problem you are seeing is one that has only been observed on NFS (network file systems) that are typically found on cluster environments. Therefore many users will never encounter this at all.
On NFS systems it is not much of a performance penalty to use IOStream (because of the way NFS works - files are already cached in memory).
On the other hand on regular filesystems there is a significant slow down when using IOStream instead of MmapIO.

**Comment by JonasIsensee** [comment] 2020-09-13 09:56
This is the most minimal version of the problem that I was able to produce:

```julia
cd(@__DIR__)

using Mmap
const MMAP_GROW_SIZE = 2^24
const FILE_GROW_SIZE = 2^18

# Byte comparision between file and copied file is not trivial on NFS if
# HEADER_SIZE % 4096 != 0
HEADER_SIZE = parse(Int, ARGS[1])

# Open the file
f = open("test.jld2"; read=true, write=true, truncate=true, create=true, append=false)

# Memory map some large region
startptr = ccall(:jl_mmap, Ptr{Cvoid}, (Ptr{Cvoid}, Csize_t, Cint, Cint, Cint, Int64),
               C_NULL, MMAP_GROW_SIZE, Mmap.PROT_WRITE,
               Mmap.MAP_SHARED, fd(f), 0)

# grow the file using pwrite
systemerror("pwrite", ccall(:jl_pwrite, Cssize_t,
                            (Cint, Ref{UInt8}, UInt, Int64),
                            fd(f), UInt8(0), 1, 2*FILE_GROW_SIZE+HEADER_SIZE-1) < 1)

# write some data (note the exact size)
cp = startptr + HEADER_SIZE
dummyarray = fill(UInt8(255), 2*FILE_GROW_SIZE)
unsafe_copyto!(convert(Ptr{UInt8},cp), Ptr{UInt8}(pointer(dummyarray)), 2*FILE_GROW_SIZE)

# now grow the file again
systemerror("pwrite", ccall(:jl_pwrite, Cssize_t,
                            (Cint, Ref{UInt8}, UInt, Int64),
                            fd(f), UInt8(0), 1, 3*FILE_GROW_SIZE+HEADER_SIZE-1) < 1)

# write some data
for i = 0:75
    cp = startptr + 2*FILE_GROW_SIZE + HEADER_SIZE + i
    unsafe_store!(convert(Ptr{UInt8},cp), UInt8(i%UInt8))
end

# call msync on the whole file
systemerror("msync",
            ccall(:msync, Cint, (Ptr{Cvoid}, Csize_t, Cint),
                  startptr , 3*FILE_GROW_SIZE+HEADER_SIZE,
                  Mmap.MS_SYNC) != 0)

# unmap the memore
systemerror("munmap",
            ccall(:munmap, Cint, (Ptr{Cvoid}, Int), startptr, MMAP_GROW_SIZE) != 0)

# close the file
close(f)
```

when I execute this file on my local cluster env as
```
julia thisfile.jl 1
cp test.jld2 test_copied.jld2
```

and then on a different machine with the same NFS mounted I get 
```
-bash-4.2$ cmp test.jld2 test_copied.jld2 -b
test.jld2 test_copied.jld2 differ: byte 524291, line 1 is   0 ^@   1 ^A
```

**Comment by JonasIsensee** [comment] 2020-09-13 16:00
> Note that references beyond the end of the object do not extend the object as the new end cannot be determined precisely by most virtual memory hardware. Instead, the size can be directly manipulated by ftruncate().
[https://pubs.opengroup.org/onlinepubs/009695399/functions/mmap.html](manpage)

**Closed** 2020-09-20 07:24 UTC
