### ISSUE TITLE
Zeros converted to missing when loading DataFrame with Union types

### ISSUE THREAD

**Issue by clint-leach** [JuliaIO/JLD2.jl#111] opened 2018-09-13 17:42 UTC
It seems that if you save and load a DataFrame that has a column with type `Union{Missing, Float64}`, any zeros in the original data get converted to `missing`.

```julia
foo = DataFrame(foo = ones(Union{Missing, Float64}, 10), bar = zeros(Union{Missing, Float64}, 10))

@save "test.jld2" foo
@load "test.jld2"
```

**Comment by ararslan** [comment] 2018-09-13 17:54
@bkamins, any idea about this, being the last one to have touched that part of the code?

**Comment by bkamins** [comment] 2018-09-13 20:47
This seems to be a bug with writing not reading as the following variables save to identical file:
```
 Union{Missing, Float64}[0.0, 0.0]
```
and
```
[0.0, missing]
```
So this is not related to the changes I made in reading.

I will have a look if I can find a problem with write (though I do not know this part of code yet).

**Comment by bkamins** [comment] 2018-09-13 23:32
I think that the problem is in this function:
https://github.com/simonster/JLD2.jl/blame/master/src/datasets.jl#L350
but not sure.

CC @simonster

**Comment by simonster** [comment] 2018-09-14 03:02
I have never used Julia 0.7/1.0 and so can't actually provide a fix, but my guess is that `unsafe_isdefined` is used in JLD2 in ways that are incompatible with the union storage optimization in Julia 0.7/1.0. You could try replacing this with `isassigned` and see if that helps. If `isassigned` is efficient now, that should be fine. Otherwise it will just make things a bit slower.

**Comment by simonster** [comment] 2018-09-14 03:12
#108 is probably the same issue. `unsafe_isdefined` assumes that it's getting handed a pointer array, but in Julia 0.7/1.0, there are arrays that are neither concretely typed nor pointer arrays, and it's probably getting those as well. These can have fewer than sizeof(Ptr{Cvoid}) bytes per element, which causes an out-of-bounds load.

**Comment by bkamins** [comment] 2018-09-14 10:19
Thanks!

**Comment by nalimilan** [comment] 2018-09-23 15:49
Maybe @quinnj could give more ideas.

**Comment by quinnj** [comment] 2018-09-23 16:05
In Base, we have `Base.isbitsunion(T)` which can be used to detect Union types that will be stored inline in an Array. There's also `Base.bitsunionsize(T)` to find out how much storage a mixed-element bits Union will take up when stored in an Array. I'm not familiar w/ JLD2's serialization strategy: is it serializing an array element by element? Or with Array metadata + inline values? `isbitstype` Union Arrays probably need to be special-cased when serializing/deserializing.

From the original report, I imagine JLD2 is storing Array metadata, then manually writing out the Array data according to offset + length. In that case, it would indeed be writing out zeros instead of missing values. Probably the best strategy would be to follow what Base does: for isbitstype Union Arrays, it writes out the array bytes, then the type tag bytes, and when deserializing, it will read the array data then the type tag data.

**Comment by bkamins** [comment] 2018-09-23 17:08
That is also my problem, that I do not know JLD2 enough to be able to help with confidence. What I know is that changing `unsafe_isdefined` to `isdefined` is not enough to fix the problem.

**Comment by tpapp** [comment] 2019-01-29 09:54
I just ran into this, is there a chance of having it fixed?

**Comment by JonasIsensee** [comment] 2019-02-16 14:50
Finally figured out that this is, what has been breaking my result (DataFrame) files
while transferring them from the cluster to my own computer.

Any workaround ideas for someone who's bound to using `julia v1.0` ? (no `serialize`)
I can't update the cluster version.

**Comment by JonasIsensee** [comment] 2020-07-16 09:25
On julia 1.4.2 and with JLD v0.1.13 I can no longer reproduce this error.
Can someone else please confirm?
If so, i will close this issue.

**Comment by JonasIsensee** [comment] 2020-07-22 07:17
Tests were added on master. I'm closing this for now.
Please open a new issue if you encounter this again.

**Closed by JonasIsensee** 2020-07-22 07:17 UTC
