### ISSUE TITLE
[Julia 1.0] Cannot load OrderedDict

### ISSUE THREAD

**Issue by getzze** [JuliaIO/JLD2.jl#123] opened 2018-11-15 10:14 UTC
I posted the issue in OrderedDict:
https://github.com/JuliaCollections/DataStructures.jl/issues/467

[EDIT: code to reproduce]
```
import DataStructures: OrderedDict
import FileIO

a = OrderedDict(i => rand(10) for i in 1:5)

FileIO.save(FileIO.File(FileIO.format"JLD2","test.jld2"), "a", a)
b = FileIO.load(FileIO.File(FileIO.format"JLD2","test.jld2"), "a")

>>>┌ Warning: type OrderedCollections.OrderedDict{Any,Any} does not exist in workspace; reconstructing
>>>└ @ JLD2 ~/.julia/packages/JLD2/KjBIK/src/data.jl:1153
>>>getfield(JLD2.ReconstructedTypes, Symbol("##OrderedCollections.OrderedDict{Any,Any}#363"))(Int32[...

```
Same as https://github.com/JuliaIO/JLD2.jl/issues/113, but with `import OrderedCollections: OrderedDict` I get the same error.
It is only working with `using OrderedCollections`.

**Comment by oxinabox** [comment] 2018-11-15 14:36
I believe this is a duplicate of #112  and  #122 
(and #113, though that never properly realizes its own cause)

If you have another example of an existing issue,
there is no need to open additional  issue,
instead you can add a comment.

**Comment by JonasIsensee** [comment] 2020-07-22 07:26
This works just fine now.

**Closed by JonasIsensee** 2020-07-22 07:26 UTC
