### ISSUE TITLE
ERROR: SystemError: realpath: No such file or directory

### ISSUE THREAD

**Issue by jwscook** [JuliaIO/JLD2.jl#155] opened 2019-11-05 19:34 UTC
This problem only began after upgrading to Catalina 10.15.1 (19B88), and is related to #153 and #118.

Using JLD2 `[033835bb] JLD2 v0.1.2` I get this error:

```
julia> using JLD2

julia> @save "tmp.jld2" 0

julia> @load "tmp.jld2" i
ERROR: SystemError: realpath: No such file or directory
Stacktrace:
 [1] #systemerror#43(::Nothing, ::Function, ::Symbol, ::Bool) at ./error.jl:134
 [2] systemerror at ./error.jl:134 [inlined]
 [3] realpath(::String) at ./path.jl:388
 [4] #jldopen#9(::Bool, ::Bool, ::Function, ::String, ::Bool, ::Bool, ::Bool, ::Type{JLD2.MmapIO}) at /Users/james/.julia/packages/JLD2/KjBIK/src/JLD2.jl:232
 [5] jldopen at /Users/james/.julia/packages/JLD2/KjBIK/src/JLD2.jl:203 [inlined] (repeats 2 times)
 [6] #jldopen#10(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::String, ::String) at /Users/james/.julia/packages/JLD2/KjBIK/src/JLD2.jl:293
 [7] jldopen at /Users/james/.julia/packages/JLD2/KjBIK/src/JLD2.jl:288 [inlined] (repeats 2 times)
 [8] #jldopen#31(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::getfield(Main, Symbol("##5#6")), ::String) at /Users/james/.julia/packages/JLD2/KjBIK/src/loadsave.jl:2
 [9] jldopen(::Function, ::String) at /Users/james/.julia/packages/JLD2/KjBIK/src/loadsave.jl:2
 [10] top-level scope at /Users/james/.julia/packages/JLD2/KjBIK/src/loadsave.jl:76
```

Version info:

```
Version 1.1.2-pre.0 (2019-05-17)
release-1.1/2aee2debbb* (fork: 117 commits, 333 days)
```

**Comment by DilumAluthge** [comment] 2019-11-15 02:33
I cannot reproduce this with Julia `master` and `JLD2#master`.

@jwscook Can you see if you can reproduce this on Julia `master` and `JLD2#master`?

```julia
DMBP:Downloads dilum$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.4.0-DEV.453 (2019-11-13)
 _/ |\__'_|_|_|\__'_|  |  Commit f196d3f387 (1 day old master)
|__/                   |

julia> versioninfo(verbose = true)
Julia Version 1.4.0-DEV.453
Commit f196d3f387 (2019-11-13 23:56 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.0.0)
  uname: Darwin 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64 i386
  CPU: Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz:
              speed         user         nice          sys         idle          irq
       #1  2600 MHz      68800 s          0 s      28828 s     188198 s          0 s
       #2  2600 MHz      25971 s          0 s      10746 s     249090 s          0 s
       #3  2600 MHz      82364 s          0 s      25425 s     178018 s          0 s
       #4  2600 MHz      25601 s          0 s      10293 s     249913 s          0 s

  Memory: 8.0 GB (969.96484375 MB free)
  Uptime: 93735.0 sec
  Load Avg:  2.01513671875  2.75439453125  3.3291015625
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)

julia> import Pkg

julia> Pkg.add(Pkg.PackageSpec(name = "JLD2", rev = "master"))
   Cloning default registries into `~/.julia`
   Cloning registry from "https://github.com/JuliaRegistries/General.git"
     Added registry `General` to `~/.julia/registries/General`
   Cloning git-repo `https://github.com/JuliaIO/JLD2.jl.git`
  Updating git-repo `https://github.com/JuliaIO/JLD2.jl.git`
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
 Installed CodecZlib ────────── v0.6.0
 Installed OrderedCollections ─ v1.1.0
 Installed FileIO ───────────── v1.0.7
 Installed TranscodingStreams ─ v0.9.5
 Installed DataStructures ───── v0.17.5
 Installed BinaryProvider ───── v0.5.8
  Updating `~/.julia/environments/v1.4/Project.toml`
  [033835bb] + JLD2 v0.1.3 #master (https://github.com/JuliaIO/JLD2.jl.git)
  Updating `~/.julia/environments/v1.4/Manifest.toml`
  [b99e7846] + BinaryProvider v0.5.8
  [944b1d66] + CodecZlib v0.6.0
  [864edb3b] + DataStructures v0.17.5
  [5789e2e9] + FileIO v1.0.7
  [033835bb] + JLD2 v0.1.3 #master (https://github.com/JuliaIO/JLD2.jl.git)
  [bac558e1] + OrderedCollections v1.1.0
  [3bb67fe8] + TranscodingStreams v0.9.5
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8ba89e20] + Distributed
  [b77e0a4c] + InteractiveUtils
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  Building CodecZlib → `~/.julia/packages/CodecZlib/5t9zO/deps/build.log`

julia> using JLD2
[ Info: Precompiling JLD2 [033835bb-8acc-5ee8-8aae-3f567f8a3819]

julia> @save "tmp.jld2" x=1

julia> @load "tmp.jld2"
1-element Array{Symbol,1}:
 Symbol("x = 1")
```

**Comment by vomout** [comment] 2019-11-16 21:09
I'm also getting this. The real cause seems to be in Julia itself on MacOS Catalina: https://github.com/JuliaLang/julia/issues/33545

**Comment by DilumAluthge** [comment] 2019-11-20 02:57
Just to be clear: everyone that is reporting this issue is able to reproduce it on Julia `master`, right?

**Comment by vomout** [comment] 2019-11-20 12:41
v1.2

**Comment by julien-vaes** [comment] 2019-11-20 15:31
Had the same issue using v1.2 after installing Catalina. I have just installed v1.3.0-rc5 and the error is gone.

**Comment by DilumAluthge** [comment] 2019-11-20 17:10
So nobody is able to reproduce this on Julia master?

**Comment by jwscook** [comment] 2019-11-21 19:13
@DilumAluthge That seems to have fixed it.

```
julia> versioninfo(verbose = true)
Julia Version 1.3.0-rc4.1
Commit 8c4656b97a (2019-10-15 14:08 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.0.0)
  uname: Darwin 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64 i386
  CPU: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz: 
              speed         user         nice          sys         idle          irq
       #1  3100 MHz    3805181 s          0 s     431960 s    4591174 s          0 s
       #2  3100 MHz    3315345 s          0 s      88999 s    5423908 s          0 s
       #3  3100 MHz    3978906 s          0 s     258481 s    4590865 s          0 s
       #4  3100 MHz    3305219 s          0 s      78580 s    5444452 s          0 s
       
  Memory: 16.0 GB (9492.03125 MB free)
  Uptime: 1.079319e6 sec
  Load Avg:  5.33251953125  2.61669921875  1.76611328125
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)

julia> import Pkg

julia> Pkg.add(Pkg.PackageSpec(name = "JLD2", rev = "master"))
  Updating git-repo `https://github.com/JuliaIO/JLD2.jl.git`
 Resolving package versions...
  Updating `~/.julia/environments/v1.3/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.3/Manifest.toml`
 [no changes]

julia> using JLD2
[ Info: Precompiling JLD2 [033835bb-8acc-5ee8-8aae-3f567f8a3819]

julia> @save "tmp.jld2" x=1

julia> @load "tmp.jld2"
1-element Array{Symbol,1}:
 Symbol("x = 1")
```

**Comment by DilumAluthge** [comment] 2019-11-21 21:26
Alright, it looks like this issue is fixed in Julia `master`.

I am going to close this issue.

If anyone is able to reproduce this bug on Julia `master`, please comment, and I will reopen this issue.

**Closed by DilumAluthge** 2019-11-21 21:26 UTC
Labels: invalid

**Comment by vomout** [comment] 2019-11-21 21:36
And when is 1.3 due? Any way to work around it in 1.2?

**Comment by DilumAluthge** [comment] 2019-11-21 21:38
You can download the latest 1.3 release candidate here: https://julialang.org/downloads/

They may eventually backport a fix to 1.0, 1.1, and 1.2.

**Comment by vomout** [comment] 2019-11-21 21:59
I'm not going to do experiments for a scientific publication on an RC.

**Comment by DilumAluthge** [comment] 2019-11-21 22:12
I guess your options are:
1. Use the release candidate.
2. Wait for 1.3 to be released.
3. Run your code on a machine that is not running macOS Catalina.
